import logging
from typing import Any

import httpx

from app.core.config import settings

logger = logging.getLogger("canva.design")


class CanvaDesignService:
    @staticmethod
    async def create_design(
        access_token: str,
        prompt: str | None = None,
        title: str | None = None,
        template_id: str | None = None,
        style: str | None = None,
        metadata: dict[str, Any] | None = None,
        design_payload: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if not access_token:
            raise ValueError("Missing Canva access token")

        url = f"{settings.CANVA_API_BASE_URL.rstrip('/')}/designs"
        if design_payload:
            payload = design_payload
        else:
            payload = {
                "name": title or f"AI Design - {prompt or 'Untitled'}",
                "description": prompt or "Generated by VedaApex",
                "metadata": metadata or {},
                "source": {"type": "api", "name": "VedaApex"},
                "data": {
                    "prompt": prompt,
                    "style": style,
                    "template_id": template_id,
                },
            }

            # Remove empty values to keep the payload clean.
            payload = {k: v for k, v in payload.items() if v is not None}
            if "data" in payload:
                payload["data"] = {k: v for k, v in payload["data"].items() if v is not None}

        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(url, json=payload, headers=headers)

        if response.status_code not in {200, 201}:
            logger.error("Canva design creation failed %s %s", response.status_code, response.text)
            raise ValueError(f"Canva design creation failed: {response.text}")

        return response.json()
