"""
Pydantic schemas for PowerPoint presentation generation.

Strictly typed models for AI-generated presentation structure.
"""

from typing import Optional, List, Literal
from pydantic import BaseModel, Field, validator
from enum import Enum


class SlideLayout(str, Enum):
    """Supported slide layout types."""
    title = "title"
    section = "section"
    content = "content"
    two_column = "two_column"
    title_and_content = "title_and_content"
    quote = "quote"
    image_with_text = "image_with_text"
    table = "table"
    chart = "chart"
    code = "code"
    conclusion = "conclusion"


class Theme(str, Enum):
    """Available presentation themes."""
    modern = "modern"
    professional = "professional"
    minimal = "minimal"
    education = "education"
    dark = "dark"


class ChartType(str, Enum):
    """Supported chart types."""
    bar = "bar"
    line = "line"
    pie = "pie"
    area = "area"


class ChartDataSeries(BaseModel):
    """Data series for a chart."""
    name: str = Field(..., max_length=100)
    values: List[float] = Field(..., min_items=1, max_items=20)


class Chart(BaseModel):
    """Chart definition for a slide."""
    type: ChartType
    title: str = Field(..., max_length=200)
    categories: List[str] = Field(..., min_items=1, max_items=20)
    series: List[ChartDataSeries] = Field(..., min_items=1, max_items=10)

    @validator('categories')
    def validate_category_length(cls, v):
        for cat in v:
            if len(cat) > 100:
                raise ValueError("Category names must be ≤ 100 characters")
        return v


class TableRow(BaseModel):
    """Single row in a table."""
    cells: List[str] = Field(..., min_items=1, max_items=10)

    @validator('cells')
    def validate_cell_content(cls, v):
        for cell in v:
            if len(cell) > 500:
                raise ValueError("Cell content must be ≤ 500 characters")
        return v


class Table(BaseModel):
    """Table definition for a slide."""
    headers: List[str] = Field(..., min_items=1, max_items=10)
    rows: List[TableRow] = Field(..., min_items=1, max_items=20)

    @validator('headers')
    def validate_header_length(cls, v):
        if len(v) > 10:
            raise ValueError("Maximum 10 columns")
        for h in v:
            if len(h) > 100:
                raise ValueError("Header names must be ≤ 100 characters")
        return v


class Slide(BaseModel):
    """Represents a single slide in the presentation."""
    slide_number: int = Field(..., ge=1, le=200)
    layout: SlideLayout
    title: str = Field(..., max_length=200)
    subtitle: Optional[str] = Field(default=None, max_length=300)
    bullets: List[str] = Field(default_factory=list, max_items=10)
    paragraphs: List[str] = Field(default_factory=list, max_items=5)
    speaker_notes: Optional[str] = Field(default=None, max_length=2000)
    image_search_queries: List[str] = Field(default_factory=list, max_items=3)
    table: Optional[Table] = Field(default=None)
    chart: Optional[Chart] = Field(default=None)
    code: Optional[str] = Field(default=None, max_length=2000)
    code_language: Optional[str] = Field(default=None, max_length=50)
    quote: Optional[str] = Field(default=None, max_length=500)
    author: Optional[str] = Field(default=None, max_length=100)
    emphasis: Optional[str] = Field(default=None)  # "bold", "italic", "highlight"

    @validator('bullets')
    def validate_bullet_length(cls, v):
        for bullet in v:
            if len(bullet) > 300:
                raise ValueError("Bullet points must be ≤ 300 characters")
        return v

    @validator('paragraphs')
    def validate_paragraph_length(cls, v):
        for para in v:
            if len(para) > 1000:
                raise ValueError("Paragraphs must be ≤ 1000 characters")
        return v


class PresentationPlan(BaseModel):
    """Complete presentation structure generated by AI."""
    title: str = Field(..., max_length=200)
    subtitle: Optional[str] = Field(default=None, max_length=300)
    author: str = Field(default="VedaApex", max_length=100)
    theme: Theme = Field(default=Theme.modern)
    language: Optional[str] = Field(default="en", max_length=10)
    slides: List[Slide] = Field(..., min_items=1, max_items=200)

    @validator('slides')
    def validate_slide_count(cls, v):
        if len(v) < 1:
            raise ValueError("Presentation must have at least 1 slide")
        if len(v) > 200:
            raise ValueError("Presentation cannot exceed 200 slides")
        # Validate slide numbers are sequential
        slide_numbers = sorted([s.slide_number for s in v])
        if slide_numbers != list(range(1, len(v) + 1)):
            raise ValueError("Slide numbers must be sequential starting from 1")
        return v


# API Request/Response Models

class PPTGenerationRequest(BaseModel):
    """Request to generate a PowerPoint presentation."""
    prompt: str = Field(..., min_length=10, max_length=2000)
    slide_count: int = Field(default=10, ge=3, le=200)
    theme: Theme = Field(default=Theme.modern)
    language: str = Field(default="English")
    include_images: bool = Field(default=True)
    include_speaker_notes: bool = Field(default=False)
    provider: Optional[str] = Field(default="auto")  # "auto", "groq", "gemini", etc.


class PPTGenerationResponse(BaseModel):
    """Response from PowerPoint generation endpoint."""
    success: bool
    presentation_id: Optional[str] = None
    attachment_id: Optional[int] = None
    filename: str
    file_size_bytes: Optional[int] = None
    status: str  # "completed", "failed"
    proxy_url: Optional[str] = None
    error_message: Optional[str] = None
